### ISSUE TITLE
Funcpack massively slows function execution instead of speeding it up

### ISSUE THREAD

**Issue by Bomret** [Azure/azure-functions-pack#33]
I have a function app that consists of five functions which performs massively slower (all individual functions are two to five times slower) when funcpacking it instead of keeping the standard deployment with the node_modules folder. It is a node function app that I cannot share unfortunately, because of business relevant code, but this is the dependencies section:

```javascript
{
  "dependencies": {
    "documentdb": "^1.12.0",
    "request": "^2.81.0",
    "request-promise": "^4.2.1",
    "lodash": "^4.17.4"
  },
  "devDependencies": {
    "husky": "^0.13.4",
    "@types/documentdb": "^1.10.1",
    "@types/lodash": "^4.14.66",
    "@types/node": "^7.0.31",
    "@types/proxyquire": "^1.3.27",
    "@types/request": "0.0.44",
    "@types/request-promise": "^4.1.34",
    "azure-functions-typescript": "0.0.1",
    "conventional-github-releaser": "^1.1.11",
    "cz-conventional-changelog": "^2.0.0",
    "gulp": "^3.9.1",
    "gulp-bump": "^2.7.0",
    "gulp-git": "^2.4.0",
    "gulp-help": "^1.6.1",
    "gulp-prompt": "^0.2.0",
    "gulp-spawn-mocha": "^3.3.0",
    "gulp-tslint": "^8.1.1",
    "gulp-typescript": "^3.1.7",
    "gulp-util": "^3.0.8",
    "istanbul": "^0.4.5",
    "merge2": "^1.1.0",
    "mocha": "^3.4.2",
    "proxyquire": "^1.8.0",
    "run-sequence": "^1.2.2",
    "should": "^11.2.1",
    "should-sinon": "0.0.5",
    "sinon": "^2.3.4",
    "tslint": "^5.5.0",
    "typescript": "^2.3.4"
  }
}
```

I have compared deploying it with `SCM_USE_FUNCPACK=1` and not setting the env var using GitHub deployment. After executing the longest running function multiple times in a row I get the following mean execution times (running on a dedicated app service plan with two S1 instances):

|Without funcpack|With funcpack|
|-----|-----|
|~4 s|~20 s|

The function gets around 30 entities from the Azure Cosmos DB (set to 1000 RU's) and concurrently 
(using `Promise.all`) fetches some metadata for those entities from another service (always has a response time of around 150-200 ms per request) and then returns those augmented results.

The shortest function in the app is around 20 loc, the longest 120 loc. The resulting packed function `index.js` is around 1.9 Mb.

I simply can't find out what makes the packed functions so slow, because the opposite is to be expected, right?
I also tried funcpacking before deployment and using the Kudu Zip API to only push what's necessary, but I get the same result as if using the `SCM_USE_FUNCPACK=1` approach.

edit: typo's and more explanations

**Comment by davidebbo** [comment]
> I simply can't find out what makes the packed functions so slow, because the opposite is to be expected, right?

Actually that's not correct. The only thing func-pack is expected to affect is the **cold start**. i.e. the time it takes to run the first function after you restart the app (or change an Azure app setting). Did you test that scenario?

But when hitting the same function repeatedly (hot run), there is no expectation that func-pack will help at all, since all modules are already loaded. I would also not expect it to be any slower, so that part is rather mysterious and you'll need to isolate a bit more. e.g.

- Find where the time is spent by tracing in key places
- What happens when you leave all the `require` calls, but remove all the logic from the function? Normally, the hot run should be extremely fast (under 100ms).

**Comment by Bomret** [comment]
@davidebbo will try those out this week and post my results here.

**Comment by Bomret** [comment]
Ok, I put everything through some testing and investigation. The fault was a very weird bug in my implementation. Now funcpack does indeed help with cold startup times!
