### ISSUE TITLE
Errors out on Linux due to line endings

### ISSUE THREAD

**Issue by tstringer** [Azure/azure-functions-pack#36]
I installed this through npm but running it on Linux (Fedora 25), I get the following error:

> /usr/bin/env: ‘node\r’: No such file or directory

It looks like this has a non-*nix standard CR in there.

**Comment by SteveALee** [comment]
I just spotted an issues change in my PR #37  [with EOL](https://github.com/Azure/azure-functions-pack/pull/37/files#diff-2cfb1554a9cbe2bf7981031a26f82e4eL2)

Looks like someone had git globally configured to save CRLF in the repo - never a good idea for OSS projects. Best to set it in the project settings. 

Also editorconfig is useful.

**Comment by christopheranderson** [comment]
This is merged in dev

**Comment by tstringer** [comment]
Awesome, thanks, @christopheranderson !! 👍 😄
