### ISSUE TITLE
Runtime fails to find the function entry points when code is built with typescript

### ISSUE THREAD

**Issue by SteveALee** [Azure/azure-functions-pack#39]
If the basic JS example code is tweaked to use the [azure-functions-typescript typings](http://azureserverless.com/2017/07/16/using-typescript-in-azure-functions/) the local runtime fails with errors and Azure gives a 500.

```
A ScriptHost error has occurred
[19/08/2017 15:55:42] Exception while executing function: Functions.test. mscorlib: Unable to determine function entry point. If multiple functions are exported, you must indicat
e the entry point, either by naming it 'run' or 'index', or by naming it explicitly via the 'entryPoint' metadata property.
```

# From TS
```
/* 231 */
/***/ (function(module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function index(context, req) {
...
/***/ (function(module, exports, __webpack_require__) {
module.exports = {
    "test": __webpack_require__(231)
}
```
# From JS 

```
/* 0 */
/***/ (function(module, exports) {
module.exports = function(context, req) {
...
/***/ (function(module, exports, __webpack_require__) {
module.exports = {
    "test": __webpack_require__(0)
}
```

The __webpack_require__ definition is the same in both, but the import ordinal is different 

The TS generated JS is different to the sample with a prefix and postscript added. both related to exports
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function index(context, req) {
... same code as sample
}
exports.index = index;
```

Hopefully is  just a matter of finding the correct module exports format for TS. It's not clear why webpack behaves differently.

Anyone have good knowledge here?

**Comment by SteveALee** [comment]
if I delete the extra lines from the packed index.js or set the TS module ot none the code still fails to find the entry point.

Crazy! 

Until resolved I'll have to go unpacked and publish all the node modules as well - sloww

**Comment by SteveALee** [comment]
The answer turns out to be simple, use the `export =` form in typescript  which resolves to `module.exports =`

eg 

```export = function index(context: HttpContext, req: IFunctionRequest): void {```

**Comment by nicojs** [comment]
Awesome! Thanks for the answer, we were looking all night for this one.

**Comment by michaelbromley** [comment]
In addition to the solution from @SteveALee, I also had to set my Webpack config (using Webpack 4.8.1) to use: `libraryTarget: 'commonjs2'`, which creates an output file with `module.exports = ...` rather than just `exports = ...` (See explanation here: https://github.com/webpack/webpack/issues/1114)

**Comment by westandy-dcp** [comment]
It's funny.  This works for serviceBusTrigger functions, but for timer trigger functions, this is not the case at all.  Consistency?
