### ISSUE TITLE
Does kudu on azure have funcpack or not??

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-functions-pack#47]
I see documentation here
https://github.com/projectkudu/kudu/wiki/Configurable-settings
indicating that I can set SCM_USE_FUNCPACK=1

This doesn't appear to have any effect. There is nothing in my azure deploy.cmd file that has anything to do with funcpack. However I do see a deploy.cmd file floating around the web that is the same version as mine (1.0.15) and does have refs to funcpack.(https://codegists.com/snippet/batchfile/deploycmd_baio_batchfile)

This is all hella confusing (typical MS). Can we get some straight answers?

**Comment by davidebbo** [comment]
I understand that running int oissues can be frustrating, but statements like **This is all hella confusing (typical MS). Can we get some straight answers?** are counter productive to trying to solve issues. Please refrain from including those if your goal is to get the issue investigated.

Yes, funcpack does get run automatically on functions repo. e.g. try pushing https://github.com/davidebbo-test/FunctionAppWithBigNpm. If you have a repo for which it doesn't work, please [share a sample repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue). Thanks.

**Comment by davidebbo** [comment]
Dup of https://github.com/projectkudu/kudu/issues/2548.

**Comment by tony-gutierrez** [comment]
Verified that funcpack does not run, and the documentation on this site is wrong, or at a minimum incomplete. There is nothing in the default deploy.cmd that does anything with regards to that env variable or funcpack. If this wasn't par for the course for everything Azure, I would be much less likely to point out the fact that it is indeed typical.

**Comment by tony-gutierrez** [comment]
If anyone else is running into this see https://github.com/projectkudu/kudu/issues/2548
