### ISSUE TITLE
Unable to resolve webpack@fulls1z3/webpack#v2.2.1-harmony

### ISSUE THREAD

**Issue by nelak** [Azure/azure-functions-pack#49]
It seems that repository: https://github.com/fulls1z3/webpack was deleted and now trying to install azure-functions-pack from npm always fails.
```
yarn add azure-functions-pack
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/fulls1z3/webpack.git
Directory: /Users/Nelak/github/connector-functions
Output:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Is there any other way to get azure-functions-pack up and running meanwhile?

**Comment by davidebbo** [comment]
@christopheranderson why is it depending on @fulls1z3's webpack and not https://github.com/webpack/webpack?

**Comment by nelak** [comment]
@fulls1z3 Thanks for the input I'll give that a try to see how it works.
Although my concern is that having git dependencies leaves you open to this issue where a package install starts failing for everyone because a git dependency has been removed.
After this I'm reconsidering taking git dependencies and even if I were to own them I'd advice against it since it may completely other packages depending on the code.

**Comment by davidebbo** [comment]
@christopheranderson just updated the latest tag to an earlier version without the issue, so it should be fixed now.

**Comment by fulls1z3** [comment]
@nelak I agree, actually I've earlier published the information about the replacement solution which works without this repo (original webpack + harmony uglify) and it was going to be depreceted and deleted after a while.

Anyway if you need any help on this topic, feel free to ask.

**Comment by nelak** [comment]
@davidebbo Cool! thanks for the quick fix 💯

**Comment by nelak** [comment]
@fulls1z3 thanks for your input @davidebbo solution has worked for me already.
The issue was reminiscent of the left-pad issue, lesson learned, I'll try to make sure to avoid using git dependencies in public packages from now on.
