### ISSUE TITLE
How to indicate a failure to application insights, AND return a custom error? 

### ISSUE THREAD

**Issue by tony-gutierrez** [Azure/azure-functions-pack#52]
https://stackoverflow.com/questions/46414162/how-to-trigger-a-failure-in-an-azure-function-http-trigger-with-a-custom-error

**Comment by tony-gutierrez** [comment]
Hello?

**Comment by davidebbo** [comment]
I don't think this question relates to func-pack, so I'm guessing you're in the wrong repo. see https://github.com/Azure/azure-functions-pack to details on what this repo is about.
