### ISSUE TITLE
Need a way to enable dirname and filename in the webpack configuration

### ISSUE THREAD

**Issue by ztoben** [Azure/azure-functions-pack#57]
I'm working on a project where it is necessary to have the relative __dirname and __filename in the webpack node configuration turned on. It seems to be hardcoded to false in the webpack-runner.ts. I would propose that it either be allowed as an option to the command pack (`-f` and `-d`), or passed through the `funcpack.config.json`.

Open to other suggestions, and also wondering why it was explicitly set to false in the first place as I think this is the default in webpack already. Would be happy to submit a PR after some discussion.

**Comment by christopheranderson** [comment]
I was looking into potentially allowing you to provide your own webpack config options that I'd just pass through and error if there is a collision with the ones I provide. That would allow for this. 

Alternatively, I'm ok with it being added to funcpack.config.json, but I'm not sure I'd want to add it as a short option in command. I'd have to think on it. 

If you code up a PR and come up with something you think works, I'll definitely review it/etc.

**Comment by ztoben** [comment]
Sure, that would work too. Short hand option would definitely not be my preference. I have the changes made in a fork on my profile from when I submitted this, but I can't submit it as a PR for some reason. Do I need to be working in a branch instead of a fork?

**Comment by christopheranderson** [comment]
There's a new feature that just got released in 1.0.0 that lets you modify the config object. https://github.com/Azure/azure-functions-pack/pull/65

Give that a shot and LMK if that doesn't work for you.
