### ISSUE TITLE
How to have environment config with function-pack?

### ISSUE THREAD

**Issue by bjornicus** [Azure/azure-functions-pack#58]
I'm deploying my node.js azure function via an 'Azure App Service Deploy' step in a VSTS release definition.  One of the things you can do in that step is "JSON variable substitution", which I was using to substitute some environment specific variables into my config.json files which my function would get by doing `let config = require('./config.json');`

Functionally, everything was working quite well, but the cold start time was *terrible* (often 25-70 seconds).  Then I found azure-function-pack, which brought the cold start time down to something more reasonable (a couple of seconds).  

Unfortunately, since I do the pack as part of my build, it packs the config.json as well, and then I can't do the JSON variable substitution during the deployment... well actually I can but the function uses the packed version and ignores the updated cofig.json file.

As a workaround I'm trying to set up my release definition to do an npm install and npm pack, which I believe should work, but really isn't ideal because it makes the release deployment significantly slower (I think).

I'm hoping maybe there's something really obvious I'm missing about how I should be supplying my environment specific config to my function apps, but if not it would be nice to be able to tell azure-function-pack to exclude my config.json files and leave them separate (even if it did something like copy them to the .funcpack directory)

**Comment by christopheranderson** [comment]
Sorry for missing this issue for so long, lots of vacation/conferences. (Also sorry for the excuse :P)

In this case, I'd use environment variables to tweak config. Alternatively, apply your config updates before packing.

Theoretically, you should be able to add it to the ignored files list, but I'll have to test that.

**Comment by bjornicus** [comment]
Thanks for the suggestion.

As far as I can gather, the way to set environment variables for a function is to put them in the application settings, which now that I look back at it looks like what I ended up doing.  The tricky part was that we have scripts which create the function app for automated creation of environments and we don't want manual steps like going to the portal and adding settings.  Unfortunately, for a new function app there are settings there that get created at app creation time, and as far as I can tell there's no way to append settings, only stomp all of them, when using a deployment template. So I had to reverse engineer how those values (e.g. for 'AzureWebJobsStorage' ) were being built ant include them in my deployment template as well.

so the resources template ends up looking like this (hoping this is useful for someone in the future):

```
{
    "parameters": {
        "name": {
            "type": "string"
        },
        "storageName": {
            "type": "string"
        },
        "mySetting": {
            "type": "string"
        }
    },
    "resources": [
        {
            "apiVersion": "2016-03-01",
            "name": "[parameters('name')]",
            "type": "Microsoft.Web/sites",
            "properties": {
                "name": "[parameters('name')]",
                "siteConfig": {
                    "appSettings": [
                        {
                            "name": "AzureWebJobsDashboard",
                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=',parameters('storageName'),';AccountKey=',listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageName')), '2015-05-01-preview').key1)]"
                        },
                        {
                            "name": "AzureWebJobsStorage",
                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=',parameters('storageName'),';AccountKey=',listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageName')), '2015-05-01-preview').key1)]"
                        },
                        {
                            "name": "FUNCTIONS_EXTENSION_VERSION",
                            "value": "~1"
                        },
                        {
                            "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
                            "value": "[concat('DefaultEndpointsProtocol=https;AccountName=',parameters('storageName'),';AccountKey=',listKeys(resourceId('Microsoft.Storage/storageAccounts', parameters('storageName')), '2015-05-01-preview').key1)]"
                        },
                        {
                            "name": "WEBSITE_CONTENTSHARE",
                            "value": "[concat(toLower(parameters('name')), 'a5e9')]"
                        },
                        {
                            "name": "WEBSITE_NODE_DEFAULT_VERSION",
                            "value": "6.5.0"
                        },
                        {
                            "name": "MY_SETTING",
                            "value": "[parameters('authHost')]"
                        }
                    ]
                },
                "clientAffinityEnabled": false
            },
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageName'))]"
            ],
            "location": "[resourceGroup().location]",
            "kind": "functionapp"
        },
        {
            "apiVersion": "2015-05-01-preview",
            "type": "Microsoft.Storage/storageAccounts",
            "name": "[parameters('storageName')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "accountType": "Standard_LRS"
            }
        },
        {
            "comments": "CORS allow origins *.",
            "type": "Microsoft.Web/sites/config",
            "name": "[concat(parameters('name'), '/web')]",
            "apiVersion": "2016-08-01",
            "properties": {
                "cors": {
                    "allowedOrigins": [
                        "*"
                    ]
                }
            },
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('name'))]"
            ]
        }
    ],
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0"
}
```

**Comment by christopheranderson** [comment]
FYI, for anyone who finds this, we also have some documentation about using ARM templates to deploy Azure Functions, (which includes the Storage dependency stuff) https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code

Alternatively, you can use the `azure-functions-core-tools` npm package which has an App Settings publisher in it, but I think the ARM method is more robust long term.

Going to close this since I think app settings and environment variables is the way to go here. Even 1 fs call for loading something like config is a pretty big slow down, so should be avoided at all costs (but is sometimes unavoidable for native modules, but some packing is better than no packing)
